CREATE TABLE OEM_Specs (
PRIMARY KEY MODEL_NAME VARCHAR(20), 
MODEL_YEAR INT, LIST_PRICE FLOAT,
AVAILABLE COLOR VARCHAR(10),
MILEAGE INT, POWER FLOAT, MAX_SPEED FLOAT);

CREATE TABLE Marketplace_Inventory (
MODEL_NAME(OEM_Specs) ON DELETE CASCADE
KMS FLOAT, MAJOR_SCRATCHES VARCHAR(50),
ORIGINAL_PAINT VARCHAR(10), NO. OF ACCIDENTS REPORTED INT,
NO. OF PREVIOUS BUYERS INT, REGISTRATION PLACE VARCHAR(20) );
                
INSERT INTO OEM_Specs ("HONDA CITY 2015", 2015, 575000, "SILVER", 21, 2000, 120);
INSERT INTO Marketplace_Inventory ("HONDA CITY 2015", 75000, "MINOR SCRATCH ON BONET", "MATTE SILVER", 2, 1, "MYSURU");

SELECT COUNT(ROWS) FROM OEM_Specs;

SELECT * FROM OEM_Specs JOIN Marketplace_Inventory 
WHERE MODEL_NAME=="HONDA CITY 2015";
