CREATE TABLE OEM_Specs (
PRIMARY KEY MODEL_NAME VARCHAR(20), 
MODEL_YEAR INT, LIST_PRICE FLOAT,
AVAILABLE COLOR VARCHAR(10),
MILEAGE INT, POWER FLOAT, MAX_SPEED FLOAT);

CREATE TABLE Marketplace_Inventory (
KMS FLOAT, MAJOR_SCRATCHES VARCHAR(50),
ORIGINAL_PAINT VARCHAR(10), NO. OF ACCIDENTS REPORTED INT,
NO. OF PREVIOUS BUYERS INT, REGISTRATION PLACE VARCHAR(20) );
